### ISSUE TITLE
Homepage background video not working. 

### ISSUE THREAD

**Issue by itstiesto** [itstiesto/TokenizedFinance-Defi-#1]
I am experiencing an issue with the background video on my website Homepage. The intended functionality is to have an autoplaying and looped video on the homepage. However, the video appears as a static image and does not play as expected. Despite trying various troubleshooting steps, the problem persists.

Feel free to fork my repo and do the required changes...your effort would be appreciated.😊

Here is a link to the video -(https://www.pexels.com/video/starry-night-sky-timelapse-5818973/) or you can use any other one of your choice.

**Comment by Deka-KEAN** [comment]
Hi @itstiesto Can you assign me this?
I have fixed it

**Comment by Deka-KEAN** [comment]
Can you plz add a tag of 'hacktoberfest-accepted' or add the ‘hacktoberfest’ topic to the repository
